### PR TITLE
[terra-form-select] MultiSelect placeholder is no longer permanently visible

### LINKED ISSUE #2624: [terra-form-select] Placeholder remains after selections
# Bug Report
MultiSelect does not remove the placeholder after a selection has been made.

## Description
In the 2.25.0 of terra-form-select, MultiSelect, after selecting options and closing the select box, the placeholder would be removed.
In 2.26.0, this same workflow would result in the placeholder remaining.

## Steps to Reproduce
1.  View the terra-ui pages for Form Select.
2. Select items in the select for "Multiple".
3. Set focus elsewhere, so the select box closes.
4. Note the placeholder remains.

It did not used to do this in older versions of the control.  

## Additional Context / Screenshots
Old example:
select 2_25

New example:
select after 2_25

## Expected Behavior
Placeholder should be removed after the options are selected and the select is "closed".

## Environment

* Component Name and Version: terra-form-select > 2.26.0
* Browser Name and Version: Safari 12
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@StephenEsser

### PR DESCRIPTION
**Pull request by dev-cprice**
### Summary
fixes #2624 

Thanks for contributing to Terra.
@cerner/terra

[CONTRIBUTORS.md]: ../CONTRIBUTORS.md
[License]: ../LICENSE

### CODE REVIEW

**Comment by mjhenkes** [comment]
Should we include a test for this?

**Comment by dev-cprice** [comment]
@mjhenkes for sure. Adding one right now

**Comment by emilyrohrbough** [comment]
Shouldn't this have changed the current screenshots for this variant?

**Comment by dev-cprice** [comment]
@emilyrohrbough none of the webdriver screenshots failed during the refactor, leading me to believe that our screenshots/testing coverage is lacking in general

**Comment by dev-cprice** [comment]
@bjankord added some wdio tests for both the `tag` and `multiple` variants to make sure the placeholder is visible without a selection and gone when a selection is made and blurred

**Pull request merged**
