### PR TITLE
Lock version at 4.10 to try to fix tests

### PR DESCRIPTION
**Pull request by mhemesath**
Locked wdio at 4.10 to see if it fixes broken tests

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
What tests seem to be broken?

**Comment by mhemesath** [comment]
I'm going to close this. I don't think the break is related to the webdriver version..

**Comment by mhemesath** [comment]
@emilyrohrbough there are weird failures happening on travis but they seem to have stopped

**Comment by emilyrohrbough** [comment]
I am noticing lint errors due to `console.log()` being added to the Alert example components. I had to add `// eslint-disable-next-line no-console` in the button PR

**Comment by mhemesath** [comment]
Lint errors or lint warnings?

**Comment by emilyrohrbough** [comment]
Lint errors. It killed my travis build

**Comment by mhemesath** [comment]
Odd, how would it have been passed for merging if they generated errors

**Pull request closed without merging**
