### PR TITLE
[form-input] File Input fixed to show selection in edge.

### LINKED ISSUE #2665: [terra-form-input] Input Type File Not Showing Selection in Edge
# Bug Report

## Description
Running in MS Edge, my team is encountering an issue with `terra-form-input` with `type=file`. After interacting with the element and selecting the file...

Expectation: The file path/name is populated on field presented.
Actual: It remains blanked.

This is exclusive to Edge.

## Steps to Reproduce
1. Add `<Input type="file" />`
2. Click the element to open file select dialog.
3. Select a file.
4. See that the file name/path is not populated as expected.

## Additional Context / Screenshots
https://kaiju.cerner.com/projects/divine-spacegodzilla-ycyTiw/workspaces/silent-ebirah-vg6RLw

## Expected Behavior
The file name/path is displayed in the element.

## Possible Solution
n/a

## Environment
* Component Name and Version: `terra-form-input@1.32.0` (Also happening in Kaiju)
* Browser Name and Version: MS Edge (44.17763.1.0)
* Node/npm Version: node 8.11.3
* Webpack Version: Yarn lock is hard to read. 3.11/3.12/4.28
* Operating System and version (desktop or mobile): Windows 10

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Fixes #2665

### CODE REVIEW

**Comment by saedar** [comment]
Would it be possible to add an example of the file input, as that was where the issue was surfaced?

**Comment by saket2403** [comment]
> Would it be possible to add an example of the file input, as that was where the issue was surfaced?

Example added in 
44f5826

**Comment by saedar** [comment]
Screen Shot 2019-10-04 at 7 42 54 AM

Noticed that the file input in Edge in the example is missing some height or something. The `Browse` text is partially cut off at the bottom.

**Comment by saket2403** [comment]
https://github.com/cerner/terra-core/blob/3d0adaaa284a8a4631b39c0f45e403eaa77b1ac0/packages/terra-form-input/src/Input.module.scss#L16

The above line is causing `Browse...` text in file input to cut off at the bottom in both IE and Edge. Can I have a new value for the `padding`? 
cc @neilpfeiffer .

**Pull request merged**
