### PR TITLE
Selection styles without responsive

### PR DESCRIPTION
**Pull request by neilpfeiffer**
Updated the finalized selection styles for terra-list and terra-table. Updated the header, subheader, border, and striped row colors for terra-table. Removed the responsive behavior from terra-table.

Also updated table subheader css class names to work with updates in PR#341.

### CODE REVIEW

**Comment by bjankord** [comment]
Travis CI doesn't look like its running on this PR, we'll need to a take a look at whats going on with that.

**Comment by emilyrohrbough** [comment]
@bjankord This PR is on my branch, not master. Could be the reason?

**Comment by bjankord** [comment]
@emilyrohrbough Yeah, looks like we have CI running only or PRs merging to master.

**Comment by neilpfeiffer** [comment]
Leave it to me to break our process. Need me to close the PR and handle a different way?

**Comment by mjhenkes** [comment]
If this PR is intended for @emilyrohrbough s branch, then this is fine. When she pulls into master we'll get the build as desired.
If this PR is intended for master, you'll have to close this PR and setup a new one on master.

**Comment by neilpfeiffer** [comment]
Not intended for master. This was purely was for @emilyrohrbough to have an easier way to review/see my changes, test, and merge into her branch accordingly.

**Pull request merged**
