### PR TITLE
Adjust colors for button 2.0 and button-group 2.0 

### PR DESCRIPTION
**Pull request by neilpfeiffer**
### Summary
Has all the changes included in #1206 and adjusts the colors for button and button group. 
Updated Readme for Button to remove reference to ability to change size.

### Additional Details

Packages Updated:
- **terra-button**
- **terra-button-group**

### CODE REVIEW

**Comment by mjhenkes** [comment]
Who UX reviews the UX reviewer?

**Comment by neilpfeiffer** [comment]
Rubber stamp I guess...

Found a bug with the Action button :Focus background-color style taking the Neutral button background-color.

**Comment by bjankord** [comment]
@neilpfeiffer Can you add the color changes to [Ben's branch](https://github.com/cerner/terra-core/tree/button-v2-uplift) and work with him so we can have 1 PR for these changes. Or if it is easier, give Ben the style changes needed and he can commit those to his branch.

**Comment by benbcai** [comment]
Or I could cherry pick Neil's changes to add to https://github.com/cerner/terra-core/pull/1206 and regenerate the wdio screenshots.

**Comment by neilpfeiffer** [comment]
I made a fix and validated the colors are all accurate with my last commit to this branch. 

@benbcai - I am going to close this PR and you can pull my changes from my branch [adjust-opensource-button-styles](https://github.com/cerner/terra-core/tree/adjust-opensource-button-styles) into yours to regenerate screenshot tests.

**Pull request closed without merging**
