### PR TITLE
Remove global base reset styles and add theming variables to additional base styles

### LINKED ISSUE #734: Remove global reset styling in base
# Issue Description
The global reset styles inside of the base component have been causing compatibility issues in various applications. We are planning to remove these styles from being applied globally to HTML elements and instead moving these type of styles to specific components which use these elements.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The following elements have no global styles applied directly to them via terra:
`h1, h2, h3, h4, h5, h6, p, img, dl, dt, dd, ol, ul, li`

## Current Behavior
The following elements have global styles applied directly to them to reset `margin`, `padding`, and `borders` to `0`:
`h1, h2, h3, h4, h5, h6, p, img, dl, dt, dd, ol, ul, li`

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Resolves #734. The global base reset styles have been removed from the Base component. Applicable styles like removing list margin / padding have been moved to specific component styles.

Theming variables have also been added to the base component to allow better flexibility and compatibility with legacy code base integration.

Global line height has been adjust to match the global line height from legacy terra. This is now themable as well so people can define global line-height adjustment as needed.

### Deployment Link
https://terra-core-deployed-pr-738.herokuapp.com/

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by ryanthemanuel** [comment]
Do we know if this breaks any tests or anything in terra-clinical?

**Comment by mmalaker** [comment]
Examples look good except for modal manager. On that page, the example buttons are slammed to the very bottom of the page. On IE and Edge, you can't see them unless you click into the page to scroll. At first I thought they weren't displaying at all. 

Also, is there a reason for the "id: root-component" text to display?

**Comment by bjankord** [comment]
@ryanthemanuel Uncertain what issues this may cause in terra-clinical. With this change, I'm planning to bump the major version of Base to v2.0.0. This _should_ allow terra-clinical components the opportunity to test Base v2.0.0 before integrating the update into the clinical components.

**Comment by bjankord** [comment]
@mmalaker I updated the modal manager example page so the example buttons are not slammed to the very bottom of the page. I also removed the text "id: root-component" from the example.

**Comment by mmalaker** [comment]
Looks good! Functional verification completed. All examples display and function correctly after these changes.

**Pull request merged**
