### PR TITLE
DO NOT MERGE - Figure out what's breaking IE

### PR DESCRIPTION
**Pull request by jmsv6d**
### Summary
Figuring out what's breaking IE

### Additional Details
If you have anything else that you think may be relevant to this issue, list it here. Additional information can help us better understand your changes and speed up the review process.

Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
I hope its not webpack 3

**Comment by mhemesath** [comment]
If I had to guess it’s postcss or autoprefixer breaking this

**Comment by mhemesath** [comment]
Can you please le

**Comment by mhemesath** [comment]
Oops accidentally closed PR, sorry. Can we please all details about whats not working? Locally when running in IE10 I just see `Syntax Error`. Is that what this issue is regarding? I heard someone mention that it was a `font-face` issue but I don't see that problem. Any details in the description would greatly help with troubleshooting this. Thanks

**Comment by mhemesath** [comment]
When I run locally it appears that babe-polyfill is failing out from  using const. I'm assuming its supposed to be transpiled. This leads me to believe the error is in one of 2 places:
1. An upgrade to a babel dependency
2. Webpack upgrade broke our babel configuration.

**Comment by mhemesath** [comment]
I think I found the issue... webpack-dev-server no longer supports enviornments without ES6 (IE < 11) https://github.com/webpack/webpack-dev-server#caveats

**Pull request closed without merging**
