### PR TITLE
[terra-form-radio] Updated legend styles for radio field to handle long text

### LINKED ISSUE #3142: terra-form-radio 'legend' does not word wrap
# Bug Report

## Description
The 'legend' prop does not word wrap when a view is shrunk and the legend is a longer string in IE 10. 

## Steps to Reproduce
1. Create a simple radio button, but in a long legend text string and shrink the view size.

## Additional Context / Screenshots
Legend text seems to be rendered as normal text; we tried some workarounds but we were unable to apply them. It was forcing a scrollbar in our examples without further tags. 

Can provide screenshots on request. 

## Expected Behavior
Legend text should wrap naturally. 

## Possible Solution
May need to wrap the legend in CSS tags if it's currently be rendered as plain text. 

## Environment
* Component Name and Version: terra-form-radio
* Browser Name and Version: IE 10
* Node/npm Version: 
* Webpack Version:
* Operating System and version (desktop or mobile): Windows

## @ Mentions
N/A

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

Added style `display: inline-block;` to legend-group to better handle long text

Closes #3142

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by jeremyfuksa — APPROVED** [review]

**Comment by supreethmr** [comment]
we might need to test the [checkbox-field](https://engineering.cerner.com/terra-ui/components/terra-form-checkbox/form-checkbox/checkbox-field) also for long text scenario in IE. since it has similar implementation for legend.

**Review by emilyrohrbough — APPROVED** [review]

**Review by tbiethman — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
@supreethmr should we log an issue to investigate and/or update if this change is needed?

**Comment by supreethmr** [comment]
> @supreethmr should we log an issue to investigate and/or update if this change is needed?

I verified in checkbox field. yes the long text does gets truncated in checkbox-field too. logged issue for checkbox-field : https://github.com/cerner/terra-core/issues/3156

**Comment by emilyrohrbough** [comment]
@supreethmr Awesome! thank you thank you! 😄

**Pull request merged**
