### PR TITLE
Explicitly set font-size / line-height for person name

### LINKED ISSUE #535: Update demographics to use heading component
# Issue Description

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

## Pull Request to resolve Issue: 
[Explicitly set font-size / line-height for person name - PR #779 ](https://github.com/cerner/terra-core/pull/779)

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Explicitly set line-height and font-size on demographics banner heading. This resolves #535 

### Deployment Link
https://terra-core-deployed-pr-779.herokuapp.com/static/#/site/demographics-banner

@cerner/terra

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
Do we still want to pull in the terra-heading component as the issue suggests? https://github.com/cerner/terra-core/issues/535

**Comment by bjankord** [comment]
@emilyrohrbough I'd prefer we set the font-size for the heading element in DemographicsBanner.scss compared to using the `<Heading />` component. This will give us more direct theming capabilities which will be scoped locally to the demographic banner styles.

**Comment by mmalaker** [comment]
Functional verification completed. Demographics examples display and function correctly after the changes.

**Comment by bjankord** [comment]
@neilpfeiffer @jordanlawrence15 This is ready for UX review now. Here is a link to the updated component: https://terra-core-deployed-pr-779.herokuapp.com/static/#/site/demographics-banner

**Comment by neilpfeiffer** [comment]
+1 for new sizes enhancements - ready to release. 

I will log a new enhancement issue to fix padding and margin em/rem variances.

**Pull request merged**
