### PR TITLE
CI/CD-NPM_auditbuild scripts

### PR DESCRIPTION
**Pull request by udaymattam**
### Summary

Creating "npm audit" during the ci/cd build

**What was changed:**

**Why it was changed:**

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [x] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-XXXX 

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by sdadn** [comment]
What is the purpose for this change?

**Comment by udaymattam** [comment]
> What is the purpose for this change?

https://jira2.cerner.com/browse/UXPLATFORM-8278 - this is a Pr audit will run when a PR builds. as of now it will give audit report & log all the vulnerabilities. if we want to fail we can fail for critical & high vulnerabilities that will be feature enhancement.

**Comment by sycombs** [comment]
> > What is the purpose for this change?
> 
> https://jira2.cerner.com/browse/UXPLATFORM-8278 - this is a Pr audit will run when a PR builds. as of now it will give audit report & log all the vulnerabilities. if we want to fail we can fail for critical & high vulnerabilities that will be feature enhancement.

Do we really want to fail builds for vulnerabilities or should we just run the audit script separately from the CI/CD periodically and log Jiras based on that?

**Comment by sdadn** [comment]
> Do we really want to fail builds for vulnerabilities or should we just run the audit script separately from the CI/CD periodically and log Jiras based on that?

Yeah I don't think we should fail builds, this will add potential blockers to merging PRs & doing releases. I also have concerns about inflating build times if we're only going to throw out warnings.

**Comment by udaymattam** [comment]
> > Do we really want to fail builds for vulnerabilities or should we just run the audit script separately from the CI/CD periodically and log Jiras based on that?
> 
> Yeah I don't think we should fail builds, this will add potential blockers to merging PRs & doing releases. I also have concerns about inflating build times if we're only going to throw out warnings.



> > > What is the purpose for this change?
> > 
> > 
> > https://jira2.cerner.com/browse/UXPLATFORM-8278 - this is a Pr audit will run when a PR builds. as of now it will give audit report & log all the vulnerabilities. if we want to fail we can fail for critical & high vulnerabilities that will be feature enhancement.
> 
> Do we really want to fail builds for vulnerabilities or should we just run the audit script separately from the CI/CD periodically and log Jiras based on that?

we are not failing the build for vulnerabilities. And compared the build time and it doesn't take much time(< 201 325ms ) . moreover it is used to see how many CVES (vulnerability's) are monitoring.

**Comment by sdadn** [comment]
If it's simply a matter of monitoring CVE's then those are output from `npm install` anyway e.g.

CleanShot 2023-10-23 at 07 57 07

`npm audit` simply gives a detailed report with potential fixes. I do not see any advantage of adding this command to the CICD when it should be run locally.

**Comment by kenk2** [comment]
Agreed with @sdadn. If we introduce this into the CI, we'll either ignore it if it doesn't fail the build or it will become a needless blocker of our work if it does.

**Pull request closed without merging**
