### PR TITLE
Enhance the display of terra-site.

### LINKED ISSUE #697: Terra Site to use squished Slide Panel
# Issue Description
The RTL/LTR and locale switchers are located at the upper left corner of the [engineering doc site](http://engineering.cerner.com/terra-core/#/site). When a selection is made and to see the change, you would then have to scroll to the component examples at the bottom of the page. To make the doc site easier to use, a squished slide panel can be used in terra-site so that the main content and panel content can scroll independently.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The list of components on the left side and the selected component content on the right side should scroll independent of each other.

## Current Behavior
Both the list of components and component content scroll together.

### PR DESCRIPTION
**Pull request by dkasper-was-taken**
### Summary
Update the display of terra-site to use a slide-panel.

Fixes #697 

I was debating taking my usual liberties with crazy colors, but I figured classy was better.

Deployment:
https://terra-core-deployed-pr-720.herokuapp.com/static/#/site

### CODE REVIEW

**Comment by dkasper-was-taken** [comment]
There are bugs in the select control and the props table that I will address that is preventing this build.

**Comment by dkasper-was-taken** [comment]
Long term we need to evaluate our usage of Base, and it's implementation of styling and customProps. In it's current form it wraps an unstyled div coming from the i18nProvider component, preventing simple usage in an application style root implementation.

**Comment by emilyrohrbough** [comment]
This looks really nice. With this addition of a header, would it make sense to move the home link to the header instead of the top of the link list?

**Comment by JakeLaCombe** [comment]
This maybe opinionated, but I feel that the gray backgrounds on the buttons inside the navigation is clashing some with the blue. Perhaps we could change the backgrounds to white instead? Here's what the hamburger button would look like.

screen shot 2017-08-14 at 9 06 17 am

**Comment by JakeLaCombe** [comment]
Looks nice!

**Pull request merged**
