### PR TITLE
Expose BlockActionFooter

### LINKED ISSUE #1640: isBlock Prop on CenteredActionFooter
# a New isBlock property on the CenteredActionFooter component

## Description
the isBlock Property will stretch the width of the children to take up the width of the parent div inside the CenteredActionFooter, right now in order to get the children to stretch to the width of the footer the parent div needs to have a style set to width:'100%', the consumer shouldn't have to set this prop in order to get the children to take up the whole width

## Additional Context / Screenshots
Here is a screenshot of what it looks like right now without setting the width of the parent div of the children to 100%:
screen shot 2018-06-22 at 10 38 17 am

this is what it should look like with an "isBlock" property:
screen shot 2018-06-22 at 5 08 20 pm

### PR DESCRIPTION
**Pull request by dev-cprice**
### Summary

* resolves #1640 
* expose `BlockActionFooter` as a first class component
* update docs

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by dev-cprice** [comment]
@emilyrohrbough the `_ActionFooterContainer` was refactored/renamed to `BlockActionFooter`. Where are you still seeing the `_ActionFooterContainer` being used/referenced?

**Comment by emilyrohrbough** [comment]
@dev-cprice Told you I was probably missing it
screen shot 2018-08-15 at 5 06 11 pm
This guy was not shouting out to me

**Comment by neilpfeiffer** [comment]
I will take a look. Thanks @bjankord

**Comment by neilpfeiffer** [comment]
Tested: PR #1771
Resolves: Issue #1640

**Reviewed:**
- exposes block style action-footer as first-class component (helpful for full-width block buttons)
- no style updates or changes (as intended)

\
\
Verified by @neilpfeiffer, Ready for Release.


**Pass** |
-----------|
UX Review|

**Comment by mmalaker** [comment]
Functional verification completed. The block action footer example displays and functions correctly.

**Pull request merged**
