### PR TITLE
[terra-search-field] Added right border to search input

### LINKED ISSUE #1730: [terra-search-field] Missing Right Border
# Feature Request

## Description
The input on [`terra-search-field`](https://engineering.cerner.com/terra-ui/#/components/terra-search-field/search-field/search-field) is missing the right border. We should update this to contain a right border, similar to [`terra-date-picker`](https://engineering.cerner.com/terra-ui/#/components/terra-date-picker/date-picker/date-picker).

### PR DESCRIPTION
**Pull request by tomleewu**
### Summary
Added right border to search field input.

Closes #1730.

### CODE REVIEW

**Comment by neilpfeiffer** [comment]
Now has a double border which is not ideal, so needs to overlap and swap z-index on focus. Some additional quick adds/fixes:

- Add (to match [terra-date-picker](https://github.com/cerner/terra-core/blob/429effcad0e96a029708b2b22341e731f323d9de/packages/terra-date-picker/src/DatePicker.module.scss#L17-L21)):
```
.input {
   ...

    &:focus {
        z-index: 1;
    }
}
```


- Update:
```
.button {
    ...
    margin-left: var(--terra-search-field-button-margin-left, -1px);
```


- And lets update any/all ems to px, since the borders and border-radiuses should stay fixed and not be relative:
```
0.25em  => 3px
0.071em => 1px

```

**Comment by yuderekyu** [comment]
@tomleewu let's update filter view with the same functionality

**Comment by neilpfeiffer** [comment]
**Reviewed:**
- all changes have been applied and looks good.

\
\
Marking as Verified, ready for Release.
 
**Pass** |
-----------|
UX Review|

**Comment by neilpfeiffer** [comment]
@bjankord ready to merge

**Pull request merged**
