### PR TITLE
Incorrectly captured signature after Device Rotation

### LINKED ISSUE #1489: Signature: Incorrect signature points after device rotation
# Issue Description

Signature is not captured correctly after rotating the device. The signature points captured and displayed are not where the user has touched on the canvas.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Signature should be correctly captured even after device rotation

## Current Behavior
Signature points and image is slightly off the more you scroll to the right the more evident this becomes.

## Steps to Reproduce
1. Open Terra-Signature example
2. Rotate device
3. Draw a signature moving to the right end of the canvas
4. Notice how the signature is at the left of where you are signing

## Environment
* Component Version: terra-signature 1.7.0
* Browser Name and Version: Safari
* Operating System and version (desktop or mobile): Mobile

### PR DESCRIPTION
**Pull request by vikonava**
### Summary
Resolves #1489

### Additional Details
Seems like the issue was that the event listener onresize gets fired immediately after rotating but right after the document has finished updating its elements on screen; ending up with an invalid width/height value being set for the canvas.

I had to do functional testing using iPad simulator to the test site running locally; since I don't believe there is a way we could properly setup a test for this.

Deployment Link:
https://terra-core-deployed-pr-1490.herokuapp.com/#/site/components/site/signature/index

### CODE REVIEW

**Comment by vikonava** [comment]
Could someone please restart the travis build? I didn't got any errors locally

**Comment by bjankord** [comment]
Build on travis CI looks to be failing with the following output:

```sh
TEST FAILURE:  1 assertions failed, 1118 passed. (8m 19s)
 ✖ nightwatch/signature-spec
   - [@medium] Draw a line signature and verify canvas (1.367s)
   Failed [equal]: ('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAGfklEQVR4Xu3UzZUURxCF0cQSTMENLJAv2IA1mMGOLVaI0yAQSANdP5lVk == 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGIAAABiCAYAAACrpQYOAAACGUlEQVR4Xu3b0W7DIAxGYfr+D71pqqq1W1ogwea3fXqNRORPB3KR3lprX)
       at Object.<anonymous> (/home/travis/build/cerner/terra-core/packages/terra-signature/tests/nightwatch/signature-spec.js:28:24)
       at endReadableNT (_stream_readable.js:1056:12)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
       at process._tickCallback (internal/process/next_tick.js:180:9)
   SKIPPED:
   - [@medium] Draw line, exit canvas to another element, then continue drawing
   - [@medium] Validates right click drawing is disabled
   - [@medium] Validates middle click drawing is disabled
```

**Comment by vikonava** [comment]
Couldn’t reproduce it locally, will dig deeper

**Comment by bjankord** [comment]
@vikonava We'll want to functionally review this before merging. Would you have some time to pair up with @mmalaker and walk through the defect / bugfix?

**Comment by mmalaker** [comment]
Functional verification completed. The signature example now displays and functions correctly when changing device orientation. Note that on smaller platforms scrolling needs to be controlled, otherwise it interferes with the signing gesture.

**Pull request merged**
