### PR TITLE
Fix button wrapping on small viewports

### LINKED ISSUE #1716: Button Group Wrapping Issue
# Bug Report

## Description
Text within the button group is wrapping, but not centered within the button (can be seen on the demo site at 320px wide)
[Terra UI](https://engineering.cerner.com/terra-ui/#/components/terra-button-group/button-group/button-group)

## Steps to Reproduce
1. Go to [Terra UI](https://engineering.cerner.com/terra-ui/#/components/terra-button-group/button-group/button-group)
2. Used Chrome inspect to reduce width to 320 px

1. Opened test harness for Orion Patient Search
2. Got to the search field page 
3. Used Chrome inspect to reduce width to 320 px 
4. Saw the text within the button groups did not wrap as expected

## Additional Context / Screenshots

Testing harness example: 
screen shot 2018-07-18 at 3 56 49 pm

Terra UI example: 
screen shot 2018-07-18 at 4 01 26 pm

## Expected Behavior
Text should center within each button group button

## Possible Solution
It looks like the span could be an issue?

screen shot 2018-07-19 at 8 26 50 am

screen shot 2018-07-19 at 8 27 43 am

## Environment
* Component Name and Version:
* Browser Name and Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Mac OS High Sierra 10.13.4 (17E199)

### PR DESCRIPTION
**Pull request by sharynneazhar**
### Summary
Fixed button wrapping by adding `display: inline-block` to button span.

Closes #1716.

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by JakeLaCombe** [comment]
Can we get a webdriver test for this scenario? I'd expect a screenshot to be needed to be changed.

**Comment by JakeLaCombe** [comment]
It may also be potentially addressed by updating the failing webdriver tests.

**Comment by bjankord** [comment]
Thanks for the contribution @sharynneazhar! Let us know if you need any assistance with code review feedback provided. Looks like there is some work around webdriver tests need with this change.

**Comment by sharynneazhar** [comment]
Looks like there are a lot of terra packages that are depending on the Button components. Working on updating the webdriver tests. 

Commit and screenshots coming soon!

**Comment by sharynneazhar** [comment]
Here are screenshots:

Local:
button-wrapping

WDIO:
button_group_wrapping default

**Comment by ChelseaRyanAnderson** [comment]
Awesome, thanks @sharynneazhar !

**Pull request merged**
