### PR TITLE
Release 12/7

### PR DESCRIPTION
**Pull request by sdadn**
### Summary

Closes #

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by supreethmr** [comment]
Finally Some. of the A11y features are getting released 🎉

**Comment by supreethmr** [comment]
@sdadn did you noticed below packages have no changes in there dependency list nor they have unreleased change entry on change log. Still they got minor version bump 
terra-action-footer
terra-breakpoints
terra-button
terra-cell-grid
terra-dropdown-button
terra-dynamic-grid
terra-I18n
terra-image
terra-switch
terra-visually-hidden-text

All of the packages don't. have any changes on their package.json other than minor version bump for itself.

**Comment by sdadn** [comment]
@supreethmr thanks for point that out. I ran the release script and these automatically got picked up. I'll go ahead and investigate why.

**Comment by sdadn** [comment]
@supreethmr Turns out there were changes to these packages in a previous PR that and the CHANGELOG entries were deleted here:
https://github.com/cerner/terra-core/pull/3659#discussion_r964136444

**Comment by sdadn** [comment]
@supreethmr Turns out there were changes to these packages in a previous PR and the CHANGELOG entries were deleted here:
https://github.com/cerner/terra-core/pull/3659#discussion_r964136444

**Pull request merged**
