### PR TITLE
Consume OCS Icons 1.26 release

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Consume latest OCS icons release

### CODE REVIEW

**Comment by ryanthemanuel** [comment]
I just received a message from someone who mentioned there is a discussion going on that the do not disturb icon is incorrect (it is square unlike all of the other "presence" icons).  Wondering if we should include those changes if necessary on this PR as well.

**Comment by bjankord** [comment]
> Wondering if we should include those changes if necessary on this PR as well.

I'll reach out to the UX team and see if they have an ETA on the update.

**Comment by mjhenkes** [comment]
v1.26 just released.
https://github.com/cerner/one-cerner-style-icons/releases/tag/v1.26

**Comment by bjankord** [comment]
@mjhenkes This PR uses the new 1.26 release: https://github.com/cerner/terra-core/pull/2519/commits/582183176de4888e51d35295dddd8499b9994bd6

**Pull request merged**
