### PR TITLE
Set webpack dev server at 2.7.1 for IE10 compatibility

### PR DESCRIPTION
**Pull request by mhemesath**
### Summary
Set webpack dev server at 2.7.1 for IE10 compatability. see https://github.com/webpack/webpack-dev-server#caveats

This should fix https://github.com/cerner/terra-core/pull/899

### CODE REVIEW

**Comment by mhemesath** [comment]
@emilyrohrbough @mjhenkes should I be adding all these `DEPENDENCIES.md` changes to the PR?

**Comment by mjhenkes** [comment]
In my opinion we should rollback the dependencies.md generation. I'm not convinced it adds value and it adds confusion.

**Comment by mhemesath** [comment]
Sounds good, but for this pull request should I include them or leave them out?

**Comment by mjhenkes** [comment]
Include them for now.

**Comment by bjankord** [comment]
> In my opinion we should rollback the dependencies.md generation. I'm not convinced it adds value and it adds confusion.

Agreed, lets get a PR to pull them out of the post install script and we can figure out how we want to display that info in the future.

**Comment by bjankord** [comment]
I've tested the deployment URL in IE10 VM, IE 11 VM, and MS Edge VM and all the doc pages loaded as expected.

**Pull request merged**
